project:
  type: website

website:
  title: "Weather Forecast"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Data
        menu:
          - href: EDA.qmd
            text: EDA
          - href: predictions.qmd
            text: Predictions
      - source.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



