project:
  type: website

website:
  title: "Weather Forecast"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example-1.Rmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



